# Generated by Django 3.1.4 on 2020-12-09 20:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.TaggedContentItem', to='tags.HierarchicalTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedcontentitem',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.contentitem'),
        ),
        migrations.AlterField(
            model_name='taggedcontentitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.hierarchicaltag'),
        ),
    ]
