# Generated by Django 3.1.4 on 2020-12-09 21:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20201209_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedContentItem', to='tags.HierarchicalTag', verbose_name='Tags'),
        ),
    ]
