# Generated by Django 3.1.4 on 2020-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20201209_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicaltag',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
