# Generated by Django 3.1.4 on 2020-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20201209_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicaltag',
            name='depth',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
