# Generated by Django 3.1.4 on 2020-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20201209_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicaltag',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
