# Generated by Django 3.1.4 on 2020-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
